version: '3'

services:
  backend:
    build:
      context: ./code/jvm
      dockerfile: Dockerfile
    image: backend-image
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=joaopedro123
      - Path=C:/Users/joaop/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0/LocalCache/local-packages/Python311/Scripts
      
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./code/js/uag-prediction-system
    image: frontend-image
    ports:
      - "8081:8081"
    depends_on:
      - backend

  database:
  
    image: postgres:latest
    container_name: uag-prediction-system-database-1
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=joaopedro123

volumes:
  pg_data:
